version: '3'
services:
  server:
    ports:
      - "621:621"
      - "40000:40000"
    command:
      - /bin/sh
      - -c
      - |
        go build -o main .  
        dlv --listen=:40000 --headless=true --api-version=2 exec /app/main serve
